name: autovista
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.3
  table_calendar: ^3.0.9
  intl: ^0.18.1
  dio: ^5.4.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  location: ^5.0.3
  url_launcher: ^6.2.5
  logger: ^2.0.2+1
  awesome_notifications: ^0.8.2
  timezone: ^0.9.2
  timeago: ^3.6.1
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - C:\Users\Arisha\Documents\8th sem\autovista_version2\lib\assets\images\flat_tire.jpg
    