// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5tnutrMltLvbtcZa5AWLVe46dHATzpE',
    appId: '1:41277522024:web:9cccd48ec622816f3e3bdd',
    messagingSenderId: '41277522024',
    projectId: 'aipushnotif',
    authDomain: 'aipushnotif.firebaseapp.com',
    storageBucket: 'aipushnotif.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq7Nqtols-tRwD_N1AoasGKdX8XWMSAkM',
    appId: '1:41277522024:android:40d8c1b443c1bc1d3e3bdd',
    messagingSenderId: '41277522024',
    projectId: 'aipushnotif',
    storageBucket: 'aipushnotif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaCoyMifZ0tjyytMDM_RsuCs7Vu7VD1Pk',
    appId: '1:41277522024:ios:ec1a9a3fc85969943e3bdd',
    messagingSenderId: '41277522024',
    projectId: 'aipushnotif',
    storageBucket: 'aipushnotif.firebasestorage.app',
    iosBundleId: 'com.example.autovista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaCoyMifZ0tjyytMDM_RsuCs7Vu7VD1Pk',
    appId: '1:41277522024:ios:ec1a9a3fc85969943e3bdd',
    messagingSenderId: '41277522024',
    projectId: 'aipushnotif',
    storageBucket: 'aipushnotif.firebasestorage.app',
    iosBundleId: 'com.example.autovista',
  );
}
